### ISSUE TITLE
Apply Fix == Develop points to a outdated version

### ISSUE THREAD

**Issue by edwin-yan** [viking1304/a1111-setup#4]
Thanks for creating this script.

I wonder if the package in the develop option is correct? It is pointing to a very outdated PyTorch compiled with a very outdated CUDA, assuming Mac does not need the one with CUDA to save some space.

https://github.com/viking1304/a1111-setup/blob/2e363e46ffbbd75aa7123445973e3c55d1ef0869/a1111-setup.sh#L148

Did you mean to use the nightly build?
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

**Comment by viking1304** [comment]
The script closely follows my step-by-step [guide](https://github.com/viking1304/a1111-setup/discussions/2).

My script does not install anything using `pip` itself. Instead, it uses the `sed` command (search and replace utility) to edit some files, so you do not need to do it manually. All the installation of Python packages is done by webui-user.sh from automatic1111.

The line you mentioned, actually just add this line

```
export TORCH_COMMAND="pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu"
```

after this part of the original webui-user.sh

```
# install command for torch
#export TORCH_COMMAND="pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113"
```

so it became this

```
# install command for torch
#export TORCH_COMMAND="pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113"
export TORCH_COMMAND="pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu"
```
When A1111 runs, it will do exactly what you wrote. It will run this:

```
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```

By default, it will do this instead:

```
# install command for torch
#export TORCH_COMMAND="pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113"
export TORCH_COMMAND="pip install torch torchvision torchaudio"
```

So, it will install the latest stable build, which is currently [2.1.2](https://github.com/pytorch/pytorch/releases/tag/v2.1.2).

My advice is to use this build instead of nightly.

I also [suggested using this version](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/14406) to the original authors.

I intentionally decided to update just webui-user.sh to keep a number of changed files to a minimum.
