### ISSUE TITLE
Can both GPU and CPU be put at work?

### ISSUE THREAD

**Issue by Teglgaard** [viking1304/a1111-setup#6]
Hi - I just want to thank you a lot. I have had many issues getting models with controlnets working and then I by coincidence stumpled upon your script which somehow fixed that. 

I can see that we are not utilizing the CPU but only GPU. I guess it is possible to use both at once? Or is that why it is failing?

**Comment by viking1304** [comment]
This script does the same things I explained in my [step-by-step guide](https://github.com/viking1304/a1111-setup/discussions/2).

In the case of Stable Diffusion, the GPU does almost all the work, so the CPU power is not really important, and it is the same on Windows, Linux, and Macs. You can use one or the other, but if you use a CPU, it will be much slower than a GPU, so I would not recommend that.

You can use the `--use-cpu` parameter to specify which task should be done with the CPU in order to lower the VRAM usage, but it is not really important on Macs.

It is mostly used like this:
`--use-cpu interrogate` - use CPU for interrogating (guessing the prompt from an image) - you can try and see if this makes any difference on your Mac
`--use-cpu all` - use CPU for everything (so GPU is not used at all) - you can try, but be prepared to for much slower generation than normal
